global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files: null
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: pushed-metrics
  scrape_interval: 15s
  static_configs:
  - targets:
    - localhost:5001
  metrics_path: /metrics
