global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files: null
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: client-seekright
  scrape_interval: 15s
  static_configs:
  - targets:
    - 192.168.3.85:8118
